### ISSUE TITLE
Event admin doesn't set `registration_open`, causing an error when saving.

### ISSUE THREAD

**Issue by cmutel** [sentier-dev/dds_registration#21]
In a fresh install (new clone, run migrations, createsuperuser, and then `runserver`), when creating a new event there is no field `registration_open`:

<img width="1284" alt="Screenshot 2024-03-14 at 12 48 58" src="https://github.com/Depart-de-Sentier/dds_registration/assets/645217/58ea16cd-9bb4-44c1-becd-52e9fc9402dd">

This leads to this field having no value, and an error when saving:

```python
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/admin/dds_registration/event/add/

Django Version: 5.0.3
Python Version: 3.12.2
Installed Applications:
['livereload',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'compressor',
 'crispy_forms',
 'crispy_bootstrap5',
 'django_registration',
 'dds_registration']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'livereload.middleware.LiveReloadScript']



Traceback (most recent call last):
  File "/Users/cmutel/virtualenvs/dds-registration/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmutel/virtualenvs/dds-registration/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmutel/virtualenvs/dds-registration/lib/python3.12/site-packages/django/contrib/admin/options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmutel/virtualenvs/dds-registration/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmutel/virtualenvs/dds-registration/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmutel/virtualenvs/dds-registration/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmutel/virtualenvs/dds-registration/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmutel/virtualenvs/dds-registration/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1945, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmutel/virtualenvs/dds-registration/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmutel/virtualenvs/dds-registration/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmutel/virtualenvs/dds-registration/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmutel/virtualenvs/dds-registration/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1804, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmutel/virtualenvs/dds-registration/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1849, in _changeform_view
    form_validated = form.is_valid()
                     ^^^^^^^^^^^^^^^
  File "/Users/cmutel/virtualenvs/dds-registration/lib/python3.12/site-packages/django/forms/forms.py", line 197, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "/Users/cmutel/virtualenvs/dds-registration/lib/python3.12/site-packages/django/forms/forms.py", line 192, in errors
    self.full_clean()
    ^^^^^^^^^^^^^^^^^
  File "/Users/cmutel/virtualenvs/dds-registration/lib/python3.12/site-packages/django/forms/forms.py", line 329, in full_clean
    self._post_clean()
    ^^^^^^^^^^^^^^^^^^
  File "/Users/cmutel/virtualenvs/dds-registration/lib/python3.12/site-packages/django/forms/models.py", line 496, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmutel/virtualenvs/dds-registration/lib/python3.12/site-packages/django/db/models/base.py", line 1527, in full_clean
    self.clean()
    ^^^^^^^^^^^^
  File "/Users/cmutel/Code/DdS/dds_registration/dds_registration/models.py", line 59, in clean
    if self.registration_close and self.registration_open >= self.registration_close:
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: TypeError at /admin/dds_registration/event/add/
Exception Value: '>=' not supported between instances of 'NoneType' and 'datetime.date'
```

**Comment by lilliputten** [comment]
Is it the same error?

`registration_open` is the auto-generated field, and I already saw it in the data. Will try to check it more carefully.

**Comment by cmutel** [comment]
Well, its technically not the same error as before because the field names changed, or at least that how it seems to me, but it is very similar.
